groups:
- name: build-images
  jobs:
  - set-self
  - build-http-resource
- name: clamav
  jobs:
  - set-self
  - clamav
- name: awslogs
  jobs:
  - set-self
  - inotify-tools
  - autoconf
- name: secureproxy
  jobs:
  - set-self
  - openresty
- name: elastalert
  jobs:
  - set-self
  - elastalert
- name: oauth2-proxy
  jobs:
  - set-self
  - oauth2-proxy
- name: terraform
  jobs:
  - set-self
  - terraform
  - terraform-provider-aws
  - terraform-provider-terraform
  - terraform-provider-template

resource_types:
- name: pypi
  type: docker-image
  source:
    repository: cfplatformeng/concourse-pypi-resource

- name: hashicorp-release
  type: docker-image
  source:
    repository: starkandwayne/hashicorp-release-resource

- name: http
  type: docker-image
  source:
    repository: 18fgsa/http-resource

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

resources:
- name: deps-config
  type: git
  source:
    uri: https://github.com/cloud-gov/cg-bosh-dependencies
    branch: master
    commit_verification_keys: ((cloud-gov-pgp-keys))

- name: http-resource-src
  type: git
  source:
    uri: https://github.com/18F/concourse-http-resource
    branch: master
    commit_verification_keys: ((cloud-gov-pgp-keys))

- name: http-resource-image
  type: docker-image
  source:
    email: ((docker-email))
    username: ((docker-username))
    password: ((docker-password))
    repository: 18fgsa/http-resource
    tag: latest

- name: clamav
  type: http
  source:
    index: https://www.clamav.net/downloads/
    uri: https://www.clamav.net/downloads/production/clamav-{version}.tar.gz
    file_name: clamav-{version}.tar.gz
    regex: 'clamav-(0\.\d+\.\d+)\.tar\.gz'

- name: inotify-tools
  type: git
  source:
    uri: https://github.com/rvoicilas/inotify-tools
    branch: master
    tag_filter: "3.*"
    check_every: 30m

- name: autoconf
  type: http
  source:
    index: https://ftp.gnu.org/gnu/autoconf/
    uri: https://ftp.gnu.org/gnu/autoconf/autoconf-{version}.tar.gz
    file_name: autoconf-{version}.tar.gz
    regex: 'autoconf-(\d+\.\d+)\.tar\.gz'

- name: openresty
  type: github-release
  source:
    user: openresty
    repository: openresty
    access_token: ((github-access-token))
    check_every: 30m

- name: elastalert
  type: pypi
  source:
    name: elastalert

- name: oauth2-proxy
  type: git
  source:
    uri: https://github.com/bitly/oauth2_proxy
    branch: master

- name: terraform
  type: hashicorp-release
  source:
    project: terraform

- name: terraform-provider-aws
  type: hashicorp-release
  source:
    project: terraform-provider-aws

- name: terraform-provider-terraform
  type: hashicorp-release
  source:
    project: terraform-provider-terraform

- name: terraform-provider-template
  type: hashicorp-release
  source:
    project: terraform-provider-template

- name: notify
  type: slack-notification
  source:
    url: ((slack-webhook-url))

jobs:
- name: set-self
  plan:
  - get: deps-config
    trigger: true
  - set_pipeline: self
    file: deps-config/ci/pipeline.yml

- name: build-http-resource
  plan:
  - get: http-resource-src
    trigger: true
  - put: http-resource-image
    params:
      build: http-resource-src

- name: clamav
  plan:
  - in_parallel:
    - get: deps-config
      passed: [set-self]
    - get: clamav
      trigger: true
  - task: create-issue
    file: deps-config/ci/create-issue.yml
    input_mapping:
      version: clamav
    params:
      OWNER: cloud-gov
      REPO: cg-clamav-boshrelease
      DEPENDENCY: clamav
      VERSION_FILE: version/version
      USERNAME: ((github-username))
      ACCESS_TOKEN: ((github-access-token))
      TAG_USER: ((github-team))
  - put: notify
    params:
      channel: '#cg-platform-news'
      username: ((slack-username))
      icon_url: ((slack-icon-url))
      text: "$BUILD_PIPELINE_NAME: New clamav dependency issue for clamav filed at $TEXT_FILE_CONTENT"
      text_file: issue/url

- name: inotify-tools
  plan:
  - in_parallel:
    - get: deps-config
      passed: [set-self]
    - get: inotify-tools
      trigger: true
  - task: grab-tag
    file: deps-config/ci/grab-tag.yml
    input_mapping:
      repo: inotify-tools
  - task: create-issue
    file: deps-config/ci/create-issue.yml
    input_mapping:
      version: tag
    params:
      OWNER: cloud-gov
      REPO: cg-awslogs-boshrelease
      DEPENDENCY: inotify-tools
      VERSION_FILE: version/tag
      USERNAME: ((github-username))
      ACCESS_TOKEN: ((github-access-token))
      TAG_USER: ((github-team))
  - put: notify
    params:
      channel: '#cg-platform-news'
      username: ((slack-username))
      icon_url: ((slack-icon-url))
      text: "$BUILD_PIPELINE_NAME: New awslogs dependency issue for inotify-tools filed at $TEXT_FILE_CONTENT"
      text_file: issue/url

- name: autoconf
  plan:
  - in_parallel:
    - get: deps-config
      passed: [set-self]
    - get: autoconf
      trigger: true
  - task: create-issue
    file: deps-config/ci/create-issue.yml
    input_mapping:
      version: autoconf
    params:
      OWNER: cloud-gov
      REPO: cg-awslogs-boshrelease
      DEPENDENCY: autoconf
      VERSION_FILE: version/version
      USERNAME: ((github-username))
      ACCESS_TOKEN: ((github-access-token))
      TAG_USER: ((github-team))
  - put: notify
    params:
      channel: '#cg-platform-news'
      username: ((slack-username))
      icon_url: ((slack-icon-url))
      text: "$BUILD_PIPELINE_NAME: New awslogs dependency issue for autoconf filed at $TEXT_FILE_CONTENT"
      text_file: issue/url


- name: openresty
  plan:
  - in_parallel:
    - get: deps-config
      passed: [set-self]
    - get: openresty
      trigger: true
      params:
        globs:
        - openresty-*.tar.gz
  - task: create-issue
    file: deps-config/ci/create-issue.yml
    input_mapping:
      version: openresty
    params:
      OWNER: cloud-gov
      REPO: cg-secureproxy-boshrelease
      DEPENDENCY: openresty
      VERSION_FILE: version/version
      USERNAME: ((github-username))
      ACCESS_TOKEN: ((github-access-token))
      TAG_USER: ((github-team))
  - put: notify
    params:
      channel: '#cg-platform-news'
      username: ((slack-username))
      icon_url: ((slack-icon-url))
      text: "$BUILD_PIPELINE_NAME: New secureproxy dependency issue for openresty filed at $TEXT_FILE_CONTENT"
      text_file: issue/url

- name: elastalert
  plan:
  - in_parallel:
    - get: deps-config
      passed: [set-self]
    - get: elastalert
      trigger: true
  - task: create-issue
    file: deps-config/ci/create-issue.yml
    input_mapping:
      version: elastalert
    params:
      OWNER: cloud-gov
      REPO: cg-secureproxy-boshrelease
      DEPENDENCY: openresty
      VERSION_FILE: version/version
      USERNAME: ((github-username))
      ACCESS_TOKEN: ((github-access-token))
      TAG_USER: ((github-team))
  - put: notify
    params:
      channel: '#cg-platform-news'
      username: ((slack-username))
      icon_url: ((slack-icon-url))
      text: "$BUILD_PIPELINE_NAME: New elastalert dependency issue for elastalert filed at $TEXT_FILE_CONTENT"
      text_file: issue/url

- name: oauth2-proxy
  plan:
  - in_parallel:
    - get: deps-config
      passed: [set-self]
    - get: oauth2-proxy
      trigger: true
  - task: grab-tag
    file: deps-config/ci/grab-tag.yml
    input_mapping:
      repo: oauth2-proxy
  - task: create-issue
    file: deps-config/ci/create-issue.yml
    input_mapping:
      version: tag
    params:
      OWNER: cloud-gov
      REPO: oauth2-proxy-boshrelease
      DEPENDENCY: oauth2-proxy
      VERSION_FILE: version/tag
      USERNAME: ((github-username))
      ACCESS_TOKEN: ((github-access-token))
      TAG_USER: ((github-team))
  - put: notify
    params:
      channel: '#cg-platform-news'
      username: ((slack-username))
      icon_url: ((slack-icon-url))
      text: "$BUILD_PIPELINE_NAME: New oauth2-proxy dependency issue for oauth2-proxy filed at $TEXT_FILE_CONTENT"
      text_file: issue/url

- name: terraform
  plan:
  - in_parallel:
    - get: deps-config
      passed: [set-self]
    - get: terraform
      trigger: true
  - task: create-issue
    file: deps-config/ci/create-issue.yml
    input_mapping:
      version: terraform
    params:
      OWNER: cloud-gov
      REPO: cg-provision
      DEPENDENCY: terraform
      VERSION_FILE: version/version
      USERNAME: ((github-username))
      ACCESS_TOKEN: ((github-access-token))
      TAG_USER: ((github-team))
  - put: notify
    params:
      channel: '#cg-platform-news'
      username: ((slack-username))
      icon_url: ((slack-icon-url))
      text: "$BUILD_PIPELINE_NAME: New terraform dependency issue filed at $TEXT_FILE_CONTENT"
      text_file: issue/url

- name: terraform-provider-aws
  plan:
  - in_parallel:
    - get: deps-config
      passed: [set-self]
    - get: terraform-provider-aws
      trigger: true
  - task: create-issue
    file: deps-config/ci/create-issue.yml
    input_mapping:
      version: terraform-provider-aws
    params:
      OWNER: cloud-gov
      REPO: cg-provision
      DEPENDENCY: terraform-provider-aws
      VERSION_FILE: version/version
      USERNAME: ((github-username))
      ACCESS_TOKEN: ((github-access-token))
      TAG_USER: ((github-team))
  - put: notify
    params:
      channel: '#cg-platform-news'
      username: ((slack-username))
      icon_url: ((slack-icon-url))
      text: "$BUILD_PIPELINE_NAME: New terraform-provider-aws dependency issue filed at $TEXT_FILE_CONTENT"
      text_file: issue/url

- name: terraform-provider-terraform
  plan:
  - in_parallel:
    - get: deps-config
      passed: [set-self]
    - get: terraform-provider-terraform
      trigger: true
  - task: create-issue
    file: deps-config/ci/create-issue.yml
    input_mapping:
      version: terraform-provider-terraform
    params:
      OWNER: cloud-gov
      REPO: cg-provision
      DEPENDENCY: terraform-provider-terraform
      VERSION_FILE: version/version
      USERNAME: ((github-username))
      ACCESS_TOKEN: ((github-access-token))
      TAG_USER: ((github-team))
  - put: notify
    params:
      channel: '#cg-platform-news'
      username: ((slack-username))
      icon_url: ((slack-icon-url))
      text: "$BUILD_PIPELINE_NAME: New terraform-provider-terraform dependency issue filed at $TEXT_FILE_CONTENT"
      text_file: issue/url

- name: terraform-provider-template
  plan:
  - in_parallel:
    - get: deps-config
      passed: [set-self]
    - get: terraform-provider-template
      trigger: true
  - task: create-issue
    file: deps-config/ci/create-issue.yml
    input_mapping:
      version: terraform-provider-template
    params:
      OWNER: cloud-gov
      REPO: cg-provision
      DEPENDENCY: terraform-provider-template
      VERSION_FILE: version/version
      USERNAME: ((github-username))
      ACCESS_TOKEN: ((github-access-token))
      TAG_USER: ((github-team))
  - put: notify
    params:
      channel: '#cg-platform-news'
      username: ((slack-username))
      icon_url: ((slack-icon-url))
      text: "$BUILD_PIPELINE_NAME: New terraform-provider-template dependency issue filed at $TEXT_FILE_CONTENT"
      text_file: issue/url
